# Generated by Django 4.2.5 on 2024-03-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abastecimento', models.DateField()),
                ('combustivel', models.CharField(choices=[('G', 'Gasolina'), ('E', 'Etanol'), ('D', 'Diesel')], max_length=1)),
                ('km_inicial', models.CharField(max_length=10)),
                ('km_final', models.CharField(max_length=10)),
                ('km_rodado', models.CharField(max_length=10)),
                ('litros_abastecidos', models.CharField(max_length=5)),
                ('custo_total', models.CharField(max_length=7)),
                ('custo_litro', models.CharField(max_length=5)),
                ('km_litro', models.CharField(max_length=5)),
                ('custo_km', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
    ]
