# Generated by Django 3.2.24 on 2024-04-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fuel',
            new_name='Abastecimento',
        ),
        migrations.RenameModel(
            old_name='Veiculo',
            new_name='Combustivel',
        ),
    ]
