# Generated by Django 3.2.24 on 2024-04-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_auto_20240406_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadCarros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=7)),
                ('ano', models.IntegerField(max_length=4)),
                ('cor', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
            ],
        ),
    ]
