# Generated by Django 3.2.24 on 2024-04-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_cadcarros'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadcarros',
            name='combustiveis',
            field=models.CharField(choices=[('G', 'Gasolina'), ('E', 'Etanol'), ('D', 'Diesel'), ('F', 'Flex')], default='Gasolina', max_length=1),
        ),
    ]
