# Generated by Django 3.2.24 on 2024-04-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0004_cadcarros_combustiveis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
    ]
