# Generated by Django 3.2.24 on 2024-04-12 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0005_tipocombustivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadcarros',
            name='combustiveis',
        ),
    ]
