# Generated by Django 3.2.24 on 2024-04-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0006_remove_cadcarros_combustiveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadcarros',
            name='tipocombustivel',
            field=models.CharField(default='Gasolina', max_length=10),
        ),
    ]
