# Generated by Django 3.2.24 on 2024-04-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0007_cadcarros_tipocombustivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abastecimento',
            name='custo_km',
        ),
        migrations.RemoveField(
            model_name='abastecimento',
            name='custo_litro',
        ),
        migrations.RemoveField(
            model_name='abastecimento',
            name='km_litro',
        ),
        migrations.RemoveField(
            model_name='abastecimento',
            name='km_rodado',
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='posto',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='veiculo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='combustivel',
            field=models.CharField(max_length=10),
        ),
    ]
