# Generated by Django 3.2.24 on 2024-04-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0013_auto_20240412_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadcarros',
            name='user',
        ),
    ]
