# Generated by Django 3.2.24 on 2024-04-13 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuel', '0014_remove_cadcarros_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadcarros',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='custo_total',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
