# Generated by Django 3.2.24 on 2024-04-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0017_alter_cadcarros_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadcarros',
            name='user',
        ),
    ]
