# Generated by Django 3.2.24 on 2024-04-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0020_auto_20240412_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='custo_total',
            field=models.FloatField(),
        ),
    ]
