# Generated by Django 3.2.24 on 2024-04-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0021_alter_abastecimento_custo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadcarros',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
