# Generated by Django 3.2.24 on 2024-05-19 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0025_consumo_carros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadcarros',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='fuel.consumo_carros'),
        ),
    ]
