# Generated by Django 3.2.24 on 2024-05-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0026_alter_cadcarros_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumo_carros',
            old_name='modelo',
            new_name='modelos',
        ),
    ]
