# Generated by Django 3.2.24 on 2024-05-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0027_rename_modelo_consumo_carros_modelos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadcarros',
            old_name='modelo',
            new_name='modelos',
        ),
    ]
