# Generated by Django 3.2.24 on 2024-05-19 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0029_alter_cadcarros_modelos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumo_carros',
            name='consumo_cidade',
        ),
        migrations.RemoveField(
            model_name='consumo_carros',
            name='consumo_estrada',
        ),
        migrations.AddField(
            model_name='consumo_carros',
            name='consumo_cidade_etanol',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consumo_carros',
            name='consumo_cidade_gasolina',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consumo_carros',
            name='consumo_estrada_etanol',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consumo_carros',
            name='consumo_estrada_gasolina',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='cadcarros',
            name='modelos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='fuel.consumo_carros'),
        ),
    ]
